### ISSUE TITLE
sourceCpp seems to reset random state

### ISSUE THREAD

**Issue by luc-vermeylen** [eddelbuettel/rcppziggurat#13]
Hi,

I found that when using sourceCpp, the random state is reset. For example, let's take this function:

```// [[Rcpp::depends(RcppZiggurat)]]
#include <Rcpp.h>
#include <Ziggurat.h>

using namespace Rcpp;
static Ziggurat::Ziggurat::Ziggurat zigg;

// [[Rcpp::export]]
double rand_number() {
  zigg.norm();
  return zigg.norm();
}
```

If i then source via sourceCpp and run the function i get the same random number each time. Only when i re-run the function without re-sourcing, i get different numbers.

How can i change this behavior so that also upon resourcing i get a new random number rather than the same? Is this intentional? If so, whats the reasoning and how can i change it?

Kind regards,
Luc[](url)

**Comment by eddelbuettel** [comment]
Good catch.  That is normal (desired) behaviour for the "usual" R RNGs to ensure proper handshake.  But because there can be corner cases where one does not want it, or if one wants to shave a microsecond, or ... we accomodated this added an option. 

But I am once again having a hard time finding _where_ exactly we documented that :-/  Hold one for a sec, and lemme poke @kevinushey ...

**Comment by eddelbuettel** [comment]
No, wait, that is something else.  I misunderstood the issue.

Let me think about this for a second, but I have the suspicion that your use of the static instance may enforce just that.

**Comment by luc-vermeylen** [comment]
Works for me! 

Thank you very much for the quick response!

Kind regards,
Luc

**Comment by eddelbuettel** [comment]
And the "real" real reason is, of course, that Ziggurat _has_ a fixed seed in its code.  

Hence the need for a setter.  Glad you're set!
