### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by vonnachtigall** [eddelbuettel/rcppziggurat#14]
When a package is compiled in Windows 10 environment using R 4.0.3, the following error appears:

* installing *source* package 'RcppZiggurat' ...
** package 'RcppZiggurat' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.3/include" -DNDEBUG -I. -I../inst/include -I'C:/Users/Paul von Nachtigall/Documents/R/win-library/4.0/Rcpp/include' -I'C:/Users/Paul von Nachtigall/Documents/R/win-library/4.0/RcppGSL/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
In file included from C:/Users/Paul von Nachtigall/Documents/R/win-library/4.0/RcppGSL/include/RcppGSL.h:25,
                 from RcppExports.cpp:4:
C:/Users/Paul von Nachtigall/Documents/R/win-library/4.0/RcppGSL/include/RcppGSLForward.h:25:10: fatal error: gsl/gsl_vector.h: No such file or directory
 #include <gsl/gsl_vector.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.3/etc/i386/Makeconf:229: RcppExports.o] Error 1
ERROR: compilation failed for package 'RcppZiggurat'
* removing 'C:/Users/Paul von Nachtigall/Documents/R/win-library/4.0/RcppZiggurat'
Warning in install.packages :
  installation of package ‘RcppZiggurat’ had non-zero exit status

**Comment by eddelbuettel** [comment]
That should not happen as the package has this line in `DESCRIPTION`:  

https://github.com/eddelbuettel/rcppziggurat/blob/e62877e810375158cdd870b987eb9fcdef5a4006/DESCRIPTION#L20

ensuring RcppGSL is present.  Which in turns requires the GSL getting you the headers.

Also note that the package was just upgraded by CRAN itself, which includes fresh tests.  So on balance I think this is a local error at your end leading me to close this.   If you have additional information or anything I overlooked feel free to reopen.

(It's been a while but I also believe I set RcppZiggurat up so that you can _use it_ and its header without recompiling it from source.  So just use the old / wait for the updated Windows binary and don't build from source if you don't have all requirements.  The Ziggurat headers are useful for you and is the compiled function.)
