### ISSUE TITLE
Missing dependency libgsl.so

### ISSUE THREAD

**Issue by trevorcampbell** [eddelbuettel/rcppziggurat#19]
Hi there -- this is an issue I originally filed in a different repository, but it seems the issue is lower-level and probably stems from this repository.

Link to that previous issue (with reprex etc) here: https://github.com/tidymodels/tidyclust/issues/127#issuecomment-1675559898

Thanks!

**Comment by eddelbuettel** [comment]
Please provide a reproducible example, the status at CRAN is clearly a counter-example:

![image](https://github.com/eddelbuettel/rcppziggurat/assets/673121/172ebc73-2552-46fa-8028-a5e5dc009324)

Also note that the DESCRIPTION clearly states _you_ need to supply the RcppGSL package which brings in the GSL (because R cannot as it cannot portable ensure system dependencies across OSs):

https://github.com/eddelbuettel/rcppziggurat/blob/02866acef184686b0e1c3e2f2e33c5cf67635959/DESCRIPTION#L22

and

https://github.com/eddelbuettel/rcppgsl/blob/cf6fb4781d62433c47303096e1f4f672bb059228/DESCRIPTION#L24

So I think this on you.

**Comment by eddelbuettel** [comment]
Mimimally viable example showing `RcppZiggurat` works:

1. Fire up `rocker/r2u` to get a self-sufficient and complete system that actually _fully_ knows and resolves dependencies
2. Install `RcppZigguarat` either from shell via `install.r RcppZiggurat` or via `install.packages("RcppZiggurat") (and see how `r2u` takes care of install the Ubuntu package `libgsl27`)
3. In R, run `library(RcppZiggurat)` followed by `RcppZiggurat::zrnormGSL(3)` and enjoy your three N(0,1) draws.

No issue here.

**Comment by eddelbuettel** [comment]
Thanks for trying RcppZiggurat.  System dependencies are hard, I have been at this via Debian for decades.  R cannot fully do this itself as (outside of specialised solutions like [r2u](https://eddelbuettel.github.io/r2u) cannot generally talk to the system.

That said, SystemRequirements are the best we have as a portable requirement, and they are used here.

**Comment by trevorcampbell** [comment]
@eddelbuettel thanks for the very prompt response. I did manage to reproduce your example using `rocker/r2u`, and indeed saw that the Ubuntu package manager handled dependencies. In contrast, doing the same on `rocker/verse:4.3.1` fails.

So, here's a question: is there any way that `RcppZiggurat` can check for a functioning GSL upon installation, and fail to install otherwise? At least that way users of downstream libraries that depend on `RcppZiggurat` will know they need GSL (whether that downstream library knows it or not).

Or even just an error message from RcppZiggurat that clearly states something like "Please install GSL" if an error occurs at runtime would be handy.

Thoughts?

**Comment by eddelbuettel** [comment]
Hi @trevorcampbell and thanks so much for circling back and even trying `r2u`.

The long and the short of it is that R cannot ensure system dependencies because R lives in user space. That is true in Windows, macOS and Linux -- and doubly so because Windows and macOS do not even have a consistent system management systems!  All this makes it very hard for R to ensure requirements are met, and writing them out in SystemRequirements: is the best we can do -- but is weak way that cannot ensure the requirement is satisfied.

I suspect that really is all that there is to it.  RcppZiggurart and RcppGSL do what they can: declare a SystemRequirements. If that is met or not _can only be ensured by the local user_.  Unless you are in the special case of `r2u` which _can_ and _does_ circle back to the system management system. But that is a (rather useful) exception and not the rule.

**Comment by eddelbuettel** [comment]
I just looked at this again (with fresher eyes) and you basically nailed a PPM/RSPM weakness that the rocker/r-verse container has as it is based on PPM/RSPM which _cannot_ guarantee SystemRequirements.  

rocker/r2u, and other containers (or full systems) has the full backing apt so it can.
