### ISSUE TITLE
Error: package 'RcppZiggurat' could not be loaded

### ISSUE THREAD

**Issue by RobinDenz1** [eddelbuettel/rcppziggurat#22]
Dear Prof. Dr. Dirk Eddelbuettel,

first of all I would like to thank you very much for the many packages you developed. They have been very helpful for me in the past.

I have stumbled on an error message that has seemingly come out of nowhere. I am the developer of the [simDAG](https://github.com/RobinDenz1/simDAG) R package, which sometimes uses the [Rfast](https://github.com/RfastOfficial/Rfast) package to do some topological sorting. That package depends on `RcppZiggurat`. Whenever `Rfast` is loaded during the github actions `devtools::check()` of my package, it fails with the error message:

```
Error: Error: package or namespace load failed for 'RcppZiggurat' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/runner/work/_temp/Library/RcppZiggurat/libs/RcppZiggurat.so':
  libgsl.so.27: cannot open shared object file: No such file or directory
Error: Error: package 'RcppZiggurat' could not be loaded
```
(see: https://github.com/RobinDenz1/simDAG/actions/runs/12545119725/job/34978826616). This *only* happens on github checks and never happens on any personal machine I have (linux or windows).

Do you perhaps have any idea why this happens? I apologize if this is not an issue with your package, I just can't seem to figure out the problem here.

Thank you very much and with kind regards,
Dr. Robin Denz

**Comment by eddelbuettel** [comment]
Hi Robin -- you did not say which OS you were on but one common way to run into this is

- you build RcppGSL (a dependency of RcppZiggurat) against the GSL verson present, say GSL 2.7.*
- the build now has a dependency on that major version libgsl.so.27
- the operating system updates to a newer release which brings in GSL 2.8
- as the operating system does not know that something installed in `/home/runner/work/_temp/Library/` has a dependency on GSL 2.7, it removes its runtime and keeps just 2.8
- and now RcppGSL no longer loads so RcppZiggurat no longer loads
- the fix is to reinstall RcppGSL from source so its links against the newer GSL 2.8 on the system.

I am pretty sure we have older issues describing just that: #20, #19, #18 are just a few.  

Another fix is to use a system such as [r2u](https://eddelbuettel.github.io/r2u) in which the _application dependencies_ are directly connected to the system package manager: your run-time of libgsl.so.27 would not have been removed.  I demonstrate that in [slides 12 and 13 of a talk on r2u](https://dirk.eddelbuettel.com/papers/ml_mlops_r2u_sep2024.pdf).

This issue is also very common for eg the spatial computing stack where eg libproj* may change, or for stringi where libiconv* change. I will close this here as it is not really anything we can do in RcppZiggurat.

**Comment by RobinDenz1** [comment]
Thank you very much for your detailed and fast response. My takeaway from this is that there is simply nothing I can do about it, since the checks do not run on my machine but on github actions, on which I cannot install or update anything. I will just skip those tests on CRAN then. Thanks!

**Comment by eddelbuettel** [comment]
That's not necessarily correct.  One frequently adapts GitHub Actions, maybe you need to inject a 'build RcppGSL from source' step.  And/or switches to an action runner that uses [r2u](https://eddelbuettel.github.io/r2u) as my [r-ci](https://eddelbuettel.github.io/r-ci) does -- for example I very recently unblocked a repo by Rob Hyndman when the default action templated wanted to recompile a package, and failed.  Having r2u supplied the binary (with correct and fully qualified dependencies) was the answer.

What is your package and/or repo?

**Comment by RobinDenz1** [comment]
I did not know that was an option. My package in question is `simDAG` (https://github.com/RobinDenz1/simDAG). I must confess that I am not very familiar with linux (and github actions) and have previously only relied on the defaults that are directly supplied by the `usethis` package. If it would be a quick fix I might do it, but considering this is only about 2 out of ~ 660 tests I'd also be fine with just skipping them.

**Comment by eddelbuettel** [comment]
Maybe it is even simpler:  you are using a premade cache, maybe forcing a cache rebuild leads to a package rebuild? 

![image](https://github.com/user-attachments/assets/37cc8384-ac7f-45bd-aa03-e266330d7865)

I really do not know as I do not like these actions (precisely because this setup is so opaque that debugging is hard).  

But eg the aforementioned repo just injected [this ci.yaml](https://github.com/robjhyndman/weird-package/blob/main/.github/workflows/ci.yaml) and when the pkgdown one still failed for the same reason injected these [three one-lineblocks in the middle in lieu of the two preceding it](https://github.com/robjhyndman/weird-package/blob/6b6d5a43d22e51fe97a5110dbfaf935f55c7b9a6/.github/workflows/pkgdown.yaml#L31-L50).  Anyway -- up to you.  If it is just two tests skipping is very much an option too.

**Comment by eddelbuettel** [comment]
Would a quick PR help you, or are you content to just skip the Rfast / RZiggurat / RcppGSL tests?

I see you have it unplugged now, but I am coming to believe (with all the caveat that I do _not_ this tool myself) this to be a bug in `pak` as used by the default action you got from `usethis`.  If you expand the details in that step, you see all the dependency resolution between the packages, the cache use ... but no installation as far as I can see of the (required, per above) shared library package `libgsl27` (ie the Ubuntu package).  Somehow it overlooks the need for it.  Maybe something you may want to bring up with that side.

I just ran one really quick check, cloned your repo, mounted it in a r2u container and ran my little script `installDeps.r` from the `littler` package -- it also relies on `remotes` to parse the DESCRIPTION and then install what is needed, and this of course does bring in `libgsl27` because we have proper dependencies in the .den binaries that `bspm` points to as part of r2u:

```
root@b5e7bc648b19:/work# time installDeps.r .                                                                                                                                                                     
rlang        (NA -> 1.1.4   ) [CRAN]                                                                                                                                                                               
lifecycle    (NA -> 1.0.4   ) [CRAN]                                                                                                                                                                               
glue         (NA -> 1.8.0   ) [CRAN]                                                                                                                                                                               
cli          (NA -> 3.6.3   ) [CRAN]                                                                                                                                                                               
Rcpp         (NA -> 1.0.13-1) [CRAN]                                                                                                                                                                               
RcppGSL      (NA -> 0.3.13  ) [CRAN]                                                                                                                                                                               
cpp11        (NA -> 0.5.1   ) [CRAN]                                                                                                                                                                               
vctrs        (NA -> 0.6.5   ) [CRAN]                                                                                                                                                                               
pkgconfig    (NA -> 2.0.3   ) [CRAN]                                                                                                                                                                               
magrittr     (NA -> 2.0.3   ) [CRAN]                                                                                                                                                                               
RcppArmad... (NA -> 14.2.2-1) [CRAN]                                                                                                                                                                               
RcppParallel (NA -> 5.1.9   ) [CRAN]                                                                                                                                                                               
RcppZiggurat (NA -> 0.1.6   ) [CRAN]                                                                                                                                                                               
igraph       (NA -> 2.1.2   ) [CRAN]                                                                                                                                                                               
Rfast        (NA -> 2.1.2   ) [CRAN]                                                                                                                                                                               
data.table   (NA -> 1.16.4  ) [CRAN]                                                                                                                                                                               
Installing 16 packages: rlang, lifecycle, glue, cli, Rcpp, RcppGSL, cpp11, vctrs, pkgconfig, magrittr, RcppArmadillo, RcppParallel, RcppZiggurat, igraph, Rfast, data.table
[... bunch of inermediate lines about archive read and downloads removed ...]
Setting up libtbbmalloc2:amd64 (2021.11.0-2ubuntu2) ...
Setting up r-cran-rcpp (1.0.13-1-1.ca2404.1) ...
Setting up r-cran-rlang (1.1.4-1.ca2404.1) ...
Setting up libgslcblas0:amd64 (2.7.1+dfsg-6ubuntu2) ...
Setting up libgsl27:amd64 (2.7.1+dfsg-6ubuntu2) ...
Setting up r-cran-data.table (1.16.4-1.ca2404.1) ...
Setting up r-cran-glue (1.8.0-1.ca2404.1) ...
Setting up r-cran-cli (3.6.3-1.ca2404.1) ...
Setting up r-cran-lifecycle (1.0.4-1.ca2404.1) ...
Setting up r-cran-pkgconfig (2.0.3-1.ca2404.1) ...
Setting up r-cran-cpp11 (0.5.1-1.ca2404.1) ...
Setting up libltdl7:amd64 (2.4.7-7build1) ...
Setting up libsuitesparseconfig7:amd64 (1:7.6.1+dfsg-1build1) ...
Setting up r-cran-rcpparmadillo (14.2.2-1-1.ca2404.1) ...
Setting up r-cran-rcppparallel (5.1.9-1.ca2404.1) ...
Setting up r-cran-magrittr (2.0.3-1.ca2404.1) ...
Setting up libxml2:amd64 (2.9.14+dfsg-1.3ubuntu3) ...
Setting up r-cran-rcppgsl (0.3.13-1.ca2404.1) ...
Setting up r-cran-vctrs (0.6.5-1.ca2404.1) ...
Setting up libamd3:amd64 (1:7.6.1+dfsg-1build1) ...
Setting up libcolamd3:amd64 (1:7.6.1+dfsg-1build1) ...
Setting up r-cran-rcppziggurat (0.1.6-1.ca2404.1) ...
Setting up libglpk40:amd64 (5.0-1build2) ...
Setting up r-cran-rfast (2.1.2-1.ca2404.1) ...
Setting up r-cran-igraph (2.1.2-1.ca2404.1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.3) ...

real    0m11.662s
user    0m6.308s
sys     0m1.896s
root@b5e7bc648b19:/work# 
```

And, of course, this creates a sufficient and working environment:

```sh
root@b5e7bc648b19:/work# R

R version 4.4.2 (2024-10-31) -- "Pile of Leaves"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(Rfast)
Loading required package: Rcpp
Loading required package: RcppZiggurat
Loading required package: RcppParallel

Attaching package: ‘RcppParallel’

The following object is masked from ‘package:Rcpp’:

    LdFlags


Rfast: 2.1.2
 ___ __ __ __ __    __ __ __ __ __ _             _               __ __ __ __ __     __ __ __ __ __ __   
|  __ __ __ __  |  |  __ __ __ __ _/            / \             |  __ __ __ __ /   /__ __ _   _ __ __\  
| |           | |  | |                         / _ \            | |                        / /          
| |           | |  | |                        / / \ \           | |                       / /          
| |           | |  | |                       / /   \ \          | |                      / /          
| |__ __ __ __| |  | |__ __ __ __           / /     \ \         | |__ __ __ __ _        / /__/\          
|    __ __ __ __|  |  __ __ __ __|         / /__ _ __\ \        |_ __ __ __ _   |      / ___  /           
|   \              | |                    / _ _ _ _ _ _ \                     | |      \/  / /       
| |\ \             | |                   / /           \ \                    | |         / /          
| | \ \            | |                  / /             \ \                   | |        / /          
| |  \ \           | |                 / /               \ \                  | |       / /          
| |   \ \__ __ _   | |                / /                 \ \     _ __ __ __ _| |      / /          
|_|    \__ __ __\  |_|               /_/                   \_\   /_ __ __ __ ___|      \/             team
> 
```

Anyway.

**Comment by eddelbuettel** [comment]
Yes, I like it too. As I quip: "r2u. Fast. Easy. Reliable. Pick all three.".   The nice thing is that eg the yaml file using it is even simpler, shorter, and with fewer knobs than the one that usethis gave you (Another PS: there may be an option to add a system dependency explicitly and/or nuke the cache.  May be worth checking the docs.)   Also you can probably also insert these lines 

```
      - name: Ensure libgsl is install
        run: sudo apt install libgsl27
```

which you would place right before the 'test' part and after the (incomplete, for you) sys deps install part.   May need a `sudo apt update -qq` as well but that should have run.  Untested so buyer beware.
